# Generated by Django 5.1.6 on 2025-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='FontAwesome or Lucide icon class name', max_length=50)),
                ('required_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('average_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('growth_potential', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
